version: "3"
services:
    suporte-quarkus-backend:
        container_name: suporte-quarkus-backend
        image: suporte-quarkus-backend:latest
        build:
            context: .
            dockerfile: src/main/docker/Dockerfile.jvm
            args:
                - JAR_FILE=target/suporte-quarkus-1.0.jar
                - CONTEXT=suporte-quarkus
        ports:
            - 8088:8080
        environment:
            - SERVER_BANCO_USUARIO=postgres
            - SERVER_BANCO_SENHA=895674
            - SERVER_BANCO_IP_PORT=cloudtecnologia.dynns.com:5432
            - SERVER_BANCO_BASE_NAME=suporte-quarkus