version: "3"
services:
    suporte-quarkus-backend:
        container_name: suporte-quarkus-backend
        image: suporte-quarkus-backend:latest
        build:
            context: .
            dockerfile: src/main/docker/Dockerfile.jvm
            args:
                - JAR_FILE=target/suporte-quarkus-backend-1.0.jar
                - CONTEXT=suporte-quarkus-backend
        ports:
            - 8088:8080
        env_file:
            - .env
        restart: always