version: "3"
services:
  sonarqube:
    container_name: SONAR
    image: sonarqube:7.9.2-community
    ports:
      - "9000:9000"
    environment:
      - sonar.jdbc.url=jdbc:postgresql://banco-sonar:5432/sonar
    restart: always
    depends_on:
      - banco-sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    networks:
      - integracao

  banco-sonar:
    container_name: BANCO-SONAR
    image: postgres
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    restart: always
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - integracao

networks:
  integracao:

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  postgresql:
  postgresql_data: