CREATE TABLE public.pessoa (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	cep varchar(8) NOT NULL,
	cpf varchar(11) NOT NULL,
	data_cadastro date NOT NULL,
	email varchar(255) NOT NULL,
	nacionalidade int4 NOT NULL,
	nome varchar(255) NOT NULL,
	telefone varchar(11) NOT NULL,
	titulo_eleitoral varchar(12) NOT NULL,
	CONSTRAINT pessoa_pkey PRIMARY KEY (id),
	CONSTRAINT uk_e9xqo3vcbnkwlue4xnu31wt05 UNIQUE (titulo_eleitoral),
	CONSTRAINT uk_gej40f8jfd5efnwlggtpwjloo UNIQUE (cpf)
);